# ----------------------------------------
# Created on: Wed Feb 19 18:06:13 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modelsim/pds2022_sp6_4/usim"
vmap  adc_e2 "D:/modelsim/pds2022_sp6_4/adc_e2"
vmap  ddc_e2 "D:/modelsim/pds2022_sp6_4/ddc_e2"
vmap  dll_e2 "D:/modelsim/pds2022_sp6_4/dll_e2"
vmap  hsstlp_lane "D:/modelsim/pds2022_sp6_4/hsstlp_lane"
vmap  hsstlp_pll "D:/modelsim/pds2022_sp6_4/hsstlp_pll"
vmap  iolhr_dft "D:/modelsim/pds2022_sp6_4/iolhr_dft"
vmap  ipal_e1 "D:/modelsim/pds2022_sp6_4/ipal_e1"
vmap  ipal_e2 "D:/modelsim/pds2022_sp6_4/ipal_e2"
vmap  iserdes_e2 "D:/modelsim/pds2022_sp6_4/iserdes_e2"
vmap  oserdes_e2 "D:/modelsim/pds2022_sp6_4/oserdes_e2"
vmap  pciegen2 "D:/modelsim/pds2022_sp6_4/pciegen2"
vlog -work work   \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/ipcore/fifo_line_buffer/rtl/ipm2l_fifo_ctrl_v1_1_fifo_line_buffer.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/ipcore/fifo_line_buffer/rtl/ipm2l_sdpram_v1_10_fifo_line_buffer.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/ipcore/fifo_line_buffer/rtl/ipm2l_fifo_v1_10_fifo_line_buffer.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/ipcore/fifo_line_buffer/fifo_line_buffer.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/img_process_tb.sv" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/video_data_gen.sv" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/RGB2YCbCr.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/matrix_3x3.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/median_filter_3x3.v" \
"D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/sort3.v" 

# ----------------------------------------
