#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Feb 19 16:55:22 2025

add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/img_process_tb.sv"
add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/video_data_gen.sv"
add_simulation "D:/2L676demo/img__ycbcr_sim_prj/img_ycbcr_sim_prj/sim/RGB2YCbCr.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/area_bin.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/binarization.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/matrix_3x3.v"
add_design D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/ipcore/fifo_matrix_buf/fifo_matrix_buf.idf
add_design D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/ipcore/fifo_line_buffer/fifo_line_buffer.idf
remove_design D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/ipcore/fifo_matrix_buf/fifo_matrix_buf.idf
remove_simulation "D:/2L676demo/img_aver_sim_prj/img_aver_sim_prj/sim/area_bin.v"
remove_simulation "D:/2L676demo/img_aver_sim_prj/img_aver_sim_prj/sim/binarization.v"
add_simulation "D:/2L676demo/img_aver_sim_prj/img_aver_sim_prj/sim/aver_milter.v"
add_simulation "D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/median_filter_3x3.v"
add_simulation "D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/sort3.v"
remove_simulation "D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/area_bin.v"
remove_simulation "D:/2L676demo/img_mid_sim_prj/img_mid_sim_prj/sim/binarization.v"
